# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161117_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tweets',
            new_name='twitter',
        ),
    ]
